import { LEVELS, PARENT, goalVersion, activeLink } from './domain.js';
import { esc, input, textarea, checkbox, option } from './ui.js';
const select=(label,name,options)=>`<label>${label}<select name="${name}">${options}</select></label>`;
const hidden=(name,value)=>`<input type="hidden" name="${name}" value="${esc(value)}">`;
export const shell=(title,type,fields)=>`<h2 id="life-dialog-title">${esc(title)}</h2><form data-life-form="${type}">${fields}<p class="life-error" role="alert"></p><div class="life-actions"><button type="button" class="secondary-button" data-life="close">취소</button><button class="primary-button" type="submit">저장</button></div></form>`;
export function linkFields(s,level,id,date) {
  const links=s.links.filter(l=>activeLink(l,date));
  const parent=links.find(l=>l.kind==='hierarchy'&&l.fromId===id)?.toId||'';
  const parents=s.goals.filter(g=>g.level===PARENT[level]&&goalVersion(g,date));
  const children=s.goals.filter(g=>PARENT[g.level]===level&&goalVersion(g,date));
  return `${level==='life'?'':select('상위 목표','parentId',option('','연결하지 않음',parent)+parents.map(g=>option(g.id,goalVersion(g,date).title,parent)).join(''))}${level==='short'?`<fieldset><legend>연결할 활동 항목</legend>${s.categories.filter(c=>!c.archived).map(c=>checkbox(c.name,'categoryIds',false,c.id)).join('')}</fieldset>`:`<fieldset><legend>연결할 하위 목표</legend>${children.length?children.map(g=>checkbox(goalVersion(g,date).title,'childIds',false,g.id)).join(''):'<p class="muted">하위 목표를 만든 후 연결할 수 있습니다.</p>'}</fieldset>`}${checkbox('위에서 선택한 연결을 적용합니다','confirmLinks')}<p class="muted">수정 시 이 목표의 기존 직접 연결은 종료됩니다. 계속 사용할 하위 목표·활동도 다시 선택하세요. 하위 목표의 다른 연결은 유지됩니다.</p>`;
}
export function goalForm(s,id,date) {
  const g=s.goals.find(g=>g.id===id),v=goalVersion(g,date)||{title:'',startDate:date,status:'active',kind:'achievement'},level=g?.level||'long';
  return shell(g?'목표와 연결 수정':'새 목표','goal',`${hidden('id',id||'')}<div class="life-fields">${input('목표 이름','title',v.title,'text','required maxlength="120"')}${g?hidden('level',level)+`<label>단계<input value="${LEVELS[level]}" disabled></label>`:select('단계','level',Object.entries(LEVELS).map(([k,n])=>option(k,n,level)).join(''))}</div>${textarea('이 목표가 중요한 이유 (선택)','reason',v.reason)}<div class="life-fields">${input('목표 시작일','startDate',v.startDate,'date','required')}${input('목표 종료일 (선택)','endDate',v.endDate,'date')}</div><div id="life-measures" ${level==='life'?'hidden':''}><div class="life-fields">${select('목표 성격','kind',option('achievement','완료형',v.kind)+option('maintenance','유지형',v.kind)+option('exploration','탐색형',v.kind))}${input('누적 시간 목표 (시간 · 선택)','hours',v.targetMinutes==null?'':v.targetMinutes/60,'number','min="0.01" step="any" placeholder="비우면 누적 시간만 표시"')}</div><div class="life-fields">${input('매일 실행 기준 (분 · 선택)','dailyMinutes',v.dailyMinutes,'number','min="1" max="1440"')}${select('상태','status',option('active','진행',v.status)+option('paused','잠시 멈춤',v.status)+option('completed','결과 확인 후 완료',v.status)+option('archived','보관',v.status))}</div><div class="life-fields">${input('결과 목표값 (선택)','resultTarget',v.resultTarget,'number','min="0.01" step="any"')}${input('결과 단위','resultUnit',v.resultUnit,'text','maxlength="30" placeholder="예: 회, 단계"')}</div><p class="muted">시간 목표 달성이 결과의 자동 완료를 뜻하지 않습니다.</p></div>${input('다음 행동 (선택)','nextAction',v.nextAction,'text','maxlength="500"')}<h3>연결 적용</h3>${input('연결·새 기준 적용일','effectiveDate',date,'date',`required max="${date}"`)}<div id="life-links">${linkFields(s,level,id,date)}</div><p class="life-notice" id="life-impact"></p>${checkbox('적용일 이후 기존 기록의 목표 집계가 바뀔 수 있음을 확인했습니다','confirmRetroactive')}${input('변경 이유 (선택)','changeNote','','text','maxlength="500"')}${checkbox('오늘 화면에 표시','showHome',s.homeGoalIds.includes(id))}`);
}
export const weightForm=date=>shell('체중 기록','weight',`<div class="life-fields">${input('측정 날짜','date',date,'date','required')}${input('실측 체중 (kg)','kg','','number','required min="1" max="500" step="0.1" inputmode="decimal"')}</div>${textarea('메모 (선택)','note')}`);
export function resultForm(s,id,date) {const v=goalVersion(s.goals.find(g=>g.id===id),date);return shell('결과 갱신','result',hidden('goalId',id)+`<p>${esc(v.title)} · 목표 ${v.resultTarget} ${esc(v.resultUnit)}</p>${input('측정 날짜','date',date,'date','required')}${input('현재까지의 전체 값','value','','number','required min="0" step="any"')}${textarea('확인한 근거 (선택)','note')}<p class="muted">2회에서 3회로 갱신하면 현재 3회입니다.</p>`);}
export const reviewForm=date=>shell('주간 점검','review',input('점검 날짜','date',date,'date','required')+textarea('계속할 것','keep')+textarea('조정할 것','adjust')+textarea('다음 행동 한 가지','next')+'<p class="muted">현재 목표 기준과 누적 시간도 함께 보관합니다.</p>');
